### ISSUE TITLE
lightgrey1 undefined in plotpreds.m function

### ISSUE THREAD

**Issue by kakearney** [somefunAgba/NLSIG-COVID19Lab#3]
The plotpred function crashes due to the lightgrey1 variable being undefined.  Full error text when triggered from within the app (default parameters):

```matlab
Unrecognized function or variable 'lightgrey1'.

Error in plotpreds (line 41)
plot(time_data,y_data,'MarkerSize',3,'Color',lightgrey1,'LineWidth',0.5);

Error in cov19_nlsigquery_applet (line 258)
figsv = plotpreds(gcf,country_code,time_data,x_data,y_data,dy_data,...

Error in nlsigcovid19lab/ModelButtonPushed (line 209)
                    cov19_nlsigquery_applet(search_code,update, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.
```

Possibly related, the same function attempts to call a routine named `pick_colours` on line 8.  The `pick_colours` script/function does not appear to be included with the packaged code.  However, because the call is wrapped in a try block without any corresponding error-catching instructions, the undefined function call fails silently.

**Comment by somefunAgba** [comment]
@kakearney, the **updated app** has not been added to git yet.
 The current one in the repo, uses the **obsolete** function calls, so does not reflect the refactored function changes.
.
pick_colours.m is present, see https://github.com/somefunAgba/NLSIG-COVID19Lab/tree/main/cvmain/plotter

**Comment by kakearney** [comment]
My mistake, it turns out the pick_colours function was never called due to the opengl command on the line preceding it.  The software option is only applicable on Windows systems; if you issue the

```matlab
opengl software
```

command on a Mac or *nix system, it will throw an error.  This would be the error message if it were not wrapped in a try block:

```matlab
Error using opengl
Switching to software OpenGL rendering is not supported on the Mac platform.

Error in plotpreds (line 7)
    opengl software; % safety

Error in cov19_nlsigquery_applet (line 344)
    figsv = plotpreds(gcf,country_code,time_data,x_data,y_data,dy_data,...

Error in covid19nlsigApp/ModelButtonPushed (line 223)
                    cov19_nlsigquery_applet(search_code,update, ...

Error in appdesigner.internal.service.AppManagementService/tryCallback (line 368)
                    callback(app, event);

Error in
matlab.apps.AppBase>@(source,event)tryCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event)
(line 37)
            newCallback = @(source,
            event)tryCallback(appdesigner.internal.service.AppManagementService.instance(),
            ...
```

I suggest removing this command throughout the code, or alternatively, marking this app as Windows-only.

**Comment by somefunAgba** [comment]
Thanks for that @kakearney. I have commented it out.
